# $6$rounds=2000000$JIr43shw5plP$XiTLGulgJnPLyIFZIh/rEavBnIWU5bK/oEakZDMgf63QJkaRJ2g7frFza8YoKy315BZotK3oBB6nEYtUNONNq1

{ ... }:

{
  users.groups = {
    alxandr = { };
    # docker = { };
    # wireshark = { };
  };

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.ryan = {
    # the hashed password with salt is generated by run `mkpasswd -m sha-512 -R2000000 -S '<SALT>' <PASSWORD>`.
    hashedPassword = "$6$rounds=2000000$JIr43shw5plP$XiTLGulgJnPLyIFZIh/rEavBnIWU5bK/oEakZDMgf63QJkaRJ2g7frFza8YoKy315BZotK3oBB6nEYtUNONNq1";
    home = "/home/alxandr";
    isNormalUser = true;
    description = "alxandr";
    extraGroups = [
      "alxandr"
      "users"
      "networkmanager"
      "wheel"
      # "docker"
      # "wireshark"
      "adbusers"
      # "libvirtd"
    ];
    openssh.authorizedKeys.keys = [
      # "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDiipi59EnVbi6bK1bGrcbfEM263wgdNfbrt6VBC1rHx ryan@ai-idols"
    ];
  };
}
