name: CI
on:
  push: {}

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@c69473f65c5db52bfd5542b6766583c43ce175f6 # main

      - name: Show flake
        run: nix flake show --extra-experimental-features pipe-operators

      - name: Check flake
        run: nix flake check --extra-experimental-features pipe-operators
