name: CI
on:
  push: {}

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Nix
        uses: DeterminateSystems/determinate-nix-action@4eea0b33e3d1f02ecfe37cf16e7204c424009606 # v3.21.0
        with:
          extra-conf: |
            keep-env-derivations = true
            keep-outputs = true

      - uses: YoloDev/actions-attic@96d2553f0175f02f07dc86dc7fe67eba05c7470d # v0.1.1
        id: attic
        with:
          server: https://attic.alxandr.me/attic/
          cacheName: alxandr
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12

      - name: Show flake
        run: nix flake show --extra-experimental-features pipe-operators

      - name: Check flake
        run: nix flake check --extra-experimental-features pipe-operators
